f_no = input("Please enter first Number")
s_no = input("Please enter Second Number")
c = int(f_no) / int(s_no)
print(c)
c = int(f_no) * int(s_no)
print(c)
c = int(f_no) + int(s_no)
print(c)
c = int(f_no) - int(s_no)
print(c)
